CREATE TABLE [MICOMPANY\hagaiweiss].[HW_v01_final_table_2017H1] (
    [promotionnumber]                       BIGINT           NULL,
    [TransactionDate]                       DATE             NULL,
    [promotionstartdate]                    DATE             NULL,
    [promotionenddate]                      DATE             NULL,
    [productnumber]                         BIGINT           NULL,
    [Branch_name_EN]                        VARCHAR (7)      NULL,
    [Real_quantity]                         DECIMAL (15, 2)  NULL,
    [Baseline_quantity]                     DECIMAL (15, 2)  NULL,
    [Promo_prijs]                           DECIMAL (33, 18) NULL,
    [Baseline_prijs]                        DECIMAL (33, 18) NULL,
    [Promo_prijs_Marge]                     DECIMAL (33, 18) NULL,
    [Baseline_prijs_marge]                  DECIMAL (33, 18) NULL,
    [Revenue_1_promotion]                   DECIMAL (15, 2)  NULL,
    [Revenue_2_subs_promo]                  DECIMAL (15, 2)  NULL,
    [Revenue_3_subs_group]                  DECIMAL (15, 2)  NOT NULL,
    [Revenue_4_promobuyer_existing]         DECIMAL (15, 2)  NOT NULL,
    [Revenue_5_promobuyer_new]              DECIMAL (15, 2)  NOT NULL,
    [Revenue_6_new_customer]                DECIMAL (15, 2)  NOT NULL,
    [Revenue_7_product_adoption]            DECIMAL (15, 2)  NOT NULL,
    [Revenue_8_hoarding]                    DECIMAL (15, 2)  NOT NULL,
    [Margin_1_promotion]                    DECIMAL (15, 2)  NULL,
    [Margin_2_subs_promo]                   DECIMAL (15, 2)  NULL,
    [Margin_3_subs_group]                   DECIMAL (15, 2)  NOT NULL,
    [Margin_4_promobuyer_existing]          DECIMAL (15, 2)  NOT NULL,
    [Margin_5_promobuyer_new]               DECIMAL (15, 2)  NOT NULL,
    [Margin_6_new_customer]                 DECIMAL (15, 2)  NOT NULL,
    [Margin_7_product_adoption]             DECIMAL (15, 2)  NOT NULL,
    [Margin_8_hoarding]                     DECIMAL (15, 2)  NOT NULL,
    [Revenue_value_effect]                  DECIMAL (22, 2)  NULL,
    [Margin_value_effect]                   DECIMAL (22, 2)  NULL,
    [purchase_price]                        FLOAT (53)       NULL,
    [A_date_from]                           INT              NULL,
    [A_date_to]                             INT              NULL,
    [A_perc]                                FLOAT (53)       NULL,
    [A_amount]                              FLOAT (53)       NULL,
    [PPP_product_A]                         FLOAT (53)       NULL,
    [Amount_tot_A]                          FLOAT (53)       NULL,
    [Perc_tot_A]                            FLOAT (53)       NULL,
    [B_date_from]                           FLOAT (53)       NULL,
    [B_date_to]                             FLOAT (53)       NULL,
    [B_perc]                                FLOAT (53)       NULL,
    [B_amount]                              FLOAT (53)       NULL,
    [PPP_product_B]                         FLOAT (53)       NULL,
    [Amount_tot_B]                          FLOAT (53)       NULL,
    [Perc_tot_B]                            FLOAT (53)       NULL,
    [D_Date_from]                           FLOAT (53)       NULL,
    [D_Date_to]                             FLOAT (53)       NULL,
    [D_Perc_participation_purchase_price]   FLOAT (53)       NULL,
    [D_Amount_participation_purchase_price] FLOAT (53)       NULL,
    [PPP_product_C]                         FLOAT (53)       NULL,
    [Amount_tot_C]                          FLOAT (53)       NULL,
    [Perc_tot_C]                            FLOAT (53)       NULL,
    [C_from date]                           FLOAT (53)       NULL,
    [C_to date]                             FLOAT (53)       NULL,
    [C_catalog price]                       FLOAT (53)       NULL,
    [C_neto price]                          FLOAT (53)       NULL,
    [D_price_per_product_D]                 FLOAT (53)       NULL,
    [Tot_D]                                 FLOAT (53)       NOT NULL,
    [tot_A]                                 FLOAT (53)       NOT NULL,
    [tot_B]                                 FLOAT (53)       NOT NULL,
    [tot_C]                                 FLOAT (53)       NOT NULL,
    [Tot_participation]                     FLOAT (53)       NOT NULL,
    [Supplier_ID]                           BIGINT           NULL,
    [Supplier_name_HE]                      NVARCHAR (255)   NULL
);

