CREATE TABLE [dbo].[GN_TargetViewTable_w_group_num] (
    [Group_name_HE]                        NVARCHAR (255)  NULL,
    [Category_name_HE]                     NVARCHAR (255)  NULL,
    [Subdepartment_name_HE]                NVARCHAR (255)  NULL,
    [department_name_HE]                   NVARCHAR (255)  NULL,
    [YTD_r1_promotion_CurrentYear]         DECIMAL (38, 2) NULL,
    [YTD_Revenue_value_effect_CurrentYear] DECIMAL (38, 2) NULL,
    [YTD_m1_promotion_CurrentYear]         DECIMAL (38, 2) NULL,
    [YTD_Margin_value_effect_CurrentYear]  DECIMAL (38, 2) NULL,
    [QTD_r1_promotion_CurrentYear]         DECIMAL (38, 2) NULL,
    [QTD_Revenue_value_effect_CurrentYear] DECIMAL (38, 2) NULL,
    [QTD_m1_promotion_CurrentYear]         DECIMAL (38, 2) NULL,
    [QTD_Margin_value_effect_CurrentYear]  DECIMAL (38, 2) NULL,
    [MTD_r1_promotion_CurrentYear]         DECIMAL (38, 2) NULL,
    [MTD_Revenue_value_effect_CurrentYear] DECIMAL (38, 2) NULL,
    [MTD_m1_promotion_CurrentYear]         DECIMAL (38, 2) NULL,
    [MTD_Margin_value_effect_CurrentYear]  DECIMAL (38, 2) NULL,
    [LM_r1_promotion_CurrentYear]          DECIMAL (38, 2) NULL,
    [LM_Revenue_value_effect_CurrentYear]  DECIMAL (38, 2) NULL,
    [LM_m1_promotion_CurrentYear]          DECIMAL (38, 2) NULL,
    [LM_Margin_value_effect_CurrentYear]   DECIMAL (38, 2) NULL,
    [LW_r1_promotion_CurrentYear]          DECIMAL (38, 2) NULL,
    [LW_Revenue_value_effect_CurrentYear]  DECIMAL (38, 2) NULL,
    [LW_m1_promotion_CurrentYear]          DECIMAL (38, 2) NULL,
    [LW_Margin_value_effect_CurrentYear]   DECIMAL (38, 2) NULL,
    [r1_promotion_LastYear]                DECIMAL (38, 2) NULL,
    [Revenue_value_effect_LastYear]        DECIMAL (38, 2) NULL,
    [YTD_Revenue_value_effect_LastYear]    DECIMAL (38, 2) NULL,
    [QTD_Revenue_value_effect_LastYear]    DECIMAL (38, 2) NULL,
    [MTD_Revenue_value_effect_LastYear]    DECIMAL (38, 2) NULL,
    [LM_Revenue_value_effect_LastYear]     DECIMAL (38, 2) NULL,
    [LW_Revenue_value_effect_LastYear]     DECIMAL (38, 2) NULL,
    [m1_promotion_LastYear]                DECIMAL (38, 2) NULL,
    [Margin_value_effect_LastYear]         DECIMAL (38, 2) NULL,
    [YTD_Margin_value_effect_LastYear]     DECIMAL (38, 2) NULL,
    [QTD_Margin_value_effect_LastYear]     DECIMAL (38, 2) NULL,
    [MTD_Margin_value_effect_LastYear]     DECIMAL (38, 2) NULL,
    [LM_Margin_value_effect_LastYear]      DECIMAL (38, 2) NULL,
    [LW_Margin_value_effect_LastYear]      DECIMAL (38, 2) NULL,
    [EndDate]                              DATE            NULL,
    [Category_Manager_name_HE]             NVARCHAR (255)  NULL,
    [Group_num]                            INT             NULL,
    [Revenue_target_groth]                 REAL            NULL,
    [Revenue_target]                       INT             NULL,
    [Margin_target_groth]                  REAL            NULL,
    [Margin_target]                        INT             NULL,
    [cat_id]                               BIGINT          NULL
);

