CREATE TABLE [dbo].[MM_1_bulkexport2017] (
    [Column 0]  DATETIME      NULL,
    [Column 1]  INT           NULL,
    [Column 2]  INT           NULL,
    [Column 3]  INT           NULL,
    [Column 4]  REAL          NULL,
    [Column 5]  DATETIME      NULL,
    [Column 6]  DATETIME      NULL,
    [Column 7]  SMALLINT      NULL,
    [Column 8]  BIGINT        NULL,
    [Column 9]  DATETIME      NULL,
    [Column 10] SMALLINT      NULL,
    [Column 11] SMALLINT      NULL,
    [Column 12] SMALLINT      NULL,
    [Column 13] SMALLINT      NULL,
    [Column 14] SMALLINT      NULL,
    [Column 15] SMALLINT      NULL,
    [Column 16] REAL          NULL,
    [Column 17] NVARCHAR (50) NULL,
    [Column 18] NVARCHAR (50) NULL,
    [Column 19] NVARCHAR (50) NULL,
    [Column 20] NVARCHAR (50) NULL,
    [Column 21] NVARCHAR (50) NULL,
    [Column 22] NVARCHAR (50) NULL,
    [Column 23] NVARCHAR (50) NULL,
    [Column 24] NVARCHAR (3)  NULL,
    [Column 25] NVARCHAR (50) NULL,
    [Column 26] NVARCHAR (3)  NULL,
    [Column 27] NVARCHAR (50) NULL,
    [Column 28] NVARCHAR (50) NULL,
    [Column 29] NVARCHAR (50) NULL,
    [Column 30] NVARCHAR (50) NULL,
    [Column 31] NVARCHAR (50) NULL,
    [Column 32] NVARCHAR (50) NULL,
    [Column 33] NVARCHAR (3)  NULL,
    [Column 34] NVARCHAR (50) NULL,
    [Column 35] NVARCHAR (3)  NULL,
    [Column 36] NVARCHAR (50) NULL,
    [Column 37] SMALLINT      NULL,
    [Column 38] NVARCHAR (50) NULL,
    [Column 39] NVARCHAR (50) NULL,
    [Column 40] NVARCHAR (50) NULL,
    [Column 41] NVARCHAR (50) NULL,
    [Column 42] NVARCHAR (50) NULL
);

