CREATE TABLE [dbo].[MM_2bulkexport2017] (
    [Column 0]  NVARCHAR (50) NULL,
    [Column 1]  NVARCHAR (50) NULL,
    [Column 2]  NVARCHAR (50) NULL,
    [Column 3]  NVARCHAR (50) NULL,
    [Column 4]  NVARCHAR (50) NULL,
    [Column 5]  NVARCHAR (50) NULL,
    [Column 6]  NVARCHAR (50) NULL,
    [Column 7]  NVARCHAR (50) NULL,
    [Column 8]  NVARCHAR (50) NULL,
    [Column 9]  NVARCHAR (50) NULL,
    [Column 10] NVARCHAR (50) NULL,
    [Column 11] NVARCHAR (50) NULL,
    [Column 12] NVARCHAR (50) NULL,
    [Column 13] NVARCHAR (50) NULL,
    [Column 14] NVARCHAR (50) NULL,
    [Column 15] NVARCHAR (50) NULL,
    [Column 16] NVARCHAR (50) NULL,
    [Column 17] NVARCHAR (50) NULL,
    [Column 18] NVARCHAR (50) NULL,
    [Column 19] NVARCHAR (50) NULL,
    [Column 20] NVARCHAR (50) NULL,
    [Column 21] NVARCHAR (50) NULL,
    [Column 22] VARCHAR (MAX) NULL,
    [Column 23] VARCHAR (MAX) NULL,
    [Column 24] VARCHAR (MAX) NULL,
    [Column 25] VARCHAR (MAX) NULL,
    [Column 26] VARCHAR (MAX) NULL,
    [Column 27] VARCHAR (MAX) NULL
);

