CREATE TABLE [dbo].[MM_bulkexport2016] (
    [Column 0]  DATETIME      NULL,
    [Column 1]  INT           NULL,
    [Column 2]  INT           NULL,
    [Column 3]  INT           NULL,
    [Column 4]  SMALLINT      NULL,
    [Column 5]  DATETIME      NULL,
    [Column 6]  DATETIME      NULL,
    [Column 7]  SMALLINT      NULL,
    [Column 8]  BIGINT        NULL,
    [Column 9]  DATETIME      NULL,
    [Column 10] SMALLINT      NULL,
    [Column 11] SMALLINT      NULL,
    [Column 12] SMALLINT      NULL,
    [Column 13] SMALLINT      NULL,
    [Column 14] SMALLINT      NULL,
    [Column 15] SMALLINT      NULL,
    [Column 16] REAL          NULL,
    [Column 17] REAL          NULL,
    [Column 18] REAL          NULL,
    [Column 19] REAL          NULL,
    [Column 20] REAL          NULL,
    [Column 21] REAL          NULL,
    [Column 22] VARCHAR (3)   NULL,
    [Column 23] VARCHAR (3)   NULL,
    [Column 24] VARCHAR (3)   NULL,
    [Column 25] REAL          NULL,
    [Column 26] REAL          NULL,
    [Column 27] REAL          NULL,
    [Column 28] REAL          NULL,
    [Column 29] REAL          NULL,
    [Column 30] REAL          NULL,
    [Column 31] NVARCHAR (3)  NULL,
    [Column 32] NVARCHAR (3)  NULL,
    [Column 33] NVARCHAR (3)  NULL,
    [Column 34] REAL          NULL,
    [Column 35] REAL          NULL,
    [Column 36] REAL          NULL,
    [Column 37] NVARCHAR (19) NULL,
    [Column 38] REAL          NULL,
    [Column 39] REAL          NULL,
    [Column 40] REAL          NULL,
    [Column 41] REAL          NULL,
    [Column 42] REAL          NULL
);

