CREATE TABLE [dbo].[MM_prom_bulkexport2017] (
    [Column 0]  DATETIME      NULL,
    [Column 1]  INT           NULL,
    [Column 2]  INT           NULL,
    [Column 3]  VARCHAR (MAX) NULL,
    [Column 4]  REAL          NULL,
    [Column 5]  DATETIME      NULL,
    [Column 6]  DATETIME      NULL,
    [Column 7]  SMALLINT      NULL,
    [Column 8]  SMALLINT      NULL,
    [Column 9]  DATETIME      NULL,
    [Column 10] SMALLINT      NULL,
    [Column 11] SMALLINT      NULL,
    [Column 12] SMALLINT      NULL,
    [Column 13] SMALLINT      NULL,
    [Column 14] SMALLINT      NULL,
    [Column 15] SMALLINT      NULL,
    [Column 16] REAL          NULL,
    [Column 17] REAL          NULL,
    [Column 18] REAL          NULL,
    [Column 19] REAL          NULL,
    [Column 20] REAL          NULL,
    [Column 21] REAL          NULL,
    [Column 22] REAL          NULL,
    [Column 23] REAL          NULL,
    [Column 24] REAL          NULL,
    [Column 25] REAL          NULL,
    [Column 26] VARCHAR (MAX) NULL
);

