CREATE TABLE [dbo].[MM_PG_baseline_validation_product] (
    [yearweek]            INT              NULL,
    [Package_number]      BIGINT           NULL,
    [FDOW]                DATE             NULL,
    [LDOW]                DATE             NULL,
    [ProductNumber]       BIGINT           NULL,
    [Branch_name_EN]      VARCHAR (7)      NULL,
    [SourceInd]           SMALLINT         NULL,
    [Baseline_days]       INT              NULL,
    [Valid_baseline_days] INT              NULL,
    [Days_in_plan]        INT              NULL,
    [Baseline_customers]  FLOAT (53)       NULL,
    [Real_customers]      INT              NULL,
    [Baseline_quantity]   FLOAT (53)       NULL,
    [Real_quantity]       FLOAT (53)       NULL,
    [Baseline_revenue]    FLOAT (53)       NULL,
    [Real_revenue]        FLOAT (53)       NULL,
    [Baseline_margin]     FLOAT (53)       NULL,
    [Real_margin]         FLOAT (53)       NULL,
    [Customers_PE]        FLOAT (53)       NULL,
    [Quantity_PE]         FLOAT (53)       NULL,
    [Revenue_PE]          FLOAT (53)       NULL,
    [Margin_PE]           FLOAT (53)       NULL,
    [1_Customers_PE]      NUMERIC (33, 20) NULL,
    [1_Quantity_PE]       FLOAT (53)       NULL,
    [1_Revenue_PE]        FLOAT (53)       NULL,
    [1_Margin_PE]         FLOAT (53)       NULL
);

