CREATE TABLE [dbo].[MM_Shuf_val] (
    [PromotionNumber]              INT           NULL,
    [ProductNumber]                BIGINT        NULL,
    [TransactionDate]              DATETIME      NULL,
    [SourceInd]                    SMALLINT      NULL,
    [PromotionNumberOriginal]      INT           NULL,
    [PromotionNumberUnv]           INT           NULL,
    [PromotionCharacteristicsType] SMALLINT      NULL,
    [PromotionStartDate]           DATETIME      NULL,
    [PromotionEndDate]             DATETIME      NULL,
    [PromotionLength]              SMALLINT      NULL,
    [ReshetMCCode]                 SMALLINT      NULL,
    [PromoTypeMCCode]              SMALLINT      NULL,
    [MultibuyQuantity]             SMALLINT      NULL,
    [PlaceMCCode]                  SMALLINT      NULL,
    [Folder]                       SMALLINT      NULL,
    [RealQuantity]                 REAL          NULL,
    [BaselineQuantity]             REAL          NULL,
    [Uplift]                       NVARCHAR (50) NULL,
    [Revenue1Promotion]            REAL          NULL,
    [Revenue2Subspromo]            REAL          NULL,
    [Revenue3Subsgroup]            REAL          NULL,
    [Revenue4PromoBuyerExist]      REAL          NULL,
    [Revenue5PromoBuyerNew]        REAL          NULL,
    [Revenue6NewCustomer]          REAL          NULL,
    [Revenue7ProductAdoption]      REAL          NULL,
    [Revenue8Hoarding]             REAL          NULL,
    [RevenueValueEffect]           REAL          NULL,
    [Margin1Promotion]             REAL          NULL,
    [Margin2SubsPromo]             REAL          NULL,
    [Margin3SubsGroup]             REAL          NULL,
    [Margin4PromoBuyerExist]       REAL          NULL,
    [Margin5PromoBuyerNew]         REAL          NULL,
    [Margin6NewCustomer]           REAL          NULL,
    [Margin7ProductAdoption]       REAL          NULL,
    [Margin8Hoarding]              REAL          NULL,
    [MarginValueEffect]            REAL          NULL,
    [SegmantMCCode]                REAL          NULL,
    [PromotionPricePerProduct]     REAL          NULL,
    [RegularPricePerProduct]       NVARCHAR (50) NULL,
    [Discount]                     NVARCHAR (50) NULL,
    [PromotionMarginPerProduct]    NVARCHAR (50) NULL,
    [RegularMarginPerProduct]      NVARCHAR (50) NULL,
    [LocationReshetCode]           SMALLINT      NULL
);

