CREATE TABLE [dbo].[PG_bulkexport_2015] (
    [export_date]                   DATETIME        NOT NULL,
    [PromotionNumber]               BIGINT          NULL,
    [PromotionNumberOriginal]       BIGINT          NULL,
    [PromotionNumberUnv]            INT             NULL,
    [PromotionCharacteristicsType]  INT             NULL,
    [PromotionStartDate]            DATE            NULL,
    [PromotionEndDate]              DATE            NULL,
    [Length]                        INT             NULL,
    [ProductNumber]                 BIGINT          NULL,
    [TransactionDate]               DATE            NULL,
    [Branch_name_EN_id]             INT             NULL,
    [SourceInd]                     INT             NULL,
    [Promotion_type_id]             INT             NULL,
    [Multibuy_quantity]             INT             NULL,
    [Place_in_store_id]             INT             NULL,
    [Folder]                        INT             NULL,
    [Real_quantity]                 DECIMAL (14, 2) NULL,
    [Baseline_quantity]             DECIMAL (14, 2) NULL,
    [Uplift]                        DECIMAL (14, 2) NULL,
    [Revenue_1_promotion]           DECIMAL (14, 2) NULL,
    [Revenue_2_subs_promo]          DECIMAL (14, 2) NULL,
    [Revenue_3_subs_group]          DECIMAL (14, 2) NULL,
    [Revenue_4_promobuyer_existing] DECIMAL (14, 2) NULL,
    [Revenue_5_promobuyer_new]      DECIMAL (14, 2) NULL,
    [Revenue_6_new_customer]        DECIMAL (14, 2) NULL,
    [Revenue_7_product_adoption]    DECIMAL (14, 2) NULL,
    [Revenue_8_hoarding]            DECIMAL (14, 2) NULL,
    [Revenue_value_effect]          DECIMAL (14, 2) NULL,
    [Margin_1_promotion]            DECIMAL (14, 2) NULL,
    [Margin_2_subs_promo]           DECIMAL (14, 2) NULL,
    [Margin_3_subs_group]           DECIMAL (14, 2) NULL,
    [Margin_4_promobuyer_existing]  DECIMAL (14, 2) NULL,
    [Margin_5_promobuyer_new]       DECIMAL (14, 2) NULL,
    [Margin_6_new_customer]         DECIMAL (14, 2) NULL,
    [Margin_7_product_adoption]     DECIMAL (14, 2) NULL,
    [Margin_8_hoarding]             DECIMAL (14, 2) NULL,
    [Margin_value_effect]           DECIMAL (14, 2) NULL,
    [Promotion_segment]             VARCHAR (19)    NULL,
    [Promotion_price_per_product]   DECIMAL (38, 6) NULL,
    [Regular_price_per_product]     DECIMAL (38, 6) NULL,
    [Discount]                      DECIMAL (38, 6) NULL,
    [Promotion_margin_per_product]  DECIMAL (38, 6) NULL,
    [Regular_margin_per_product]    DECIMAL (38, 6) NULL
);

