CREATE TABLE [dbo].[TC_Participation_analysis_2w] (
    [promotionnumber]           BIGINT          NULL,
    [TransactionDate]           DATE            NULL,
    [promotionstartdate]        DATE            NULL,
    [promotionenddate]          DATE            NULL,
    [productnumber]             BIGINT          NULL,
    [Branch_name_EN]            VARCHAR (7)     NULL,
    [SourceInd]                 SMALLINT        NULL,
    [Supplier_ID]               INT             NULL,
    [Supplier_name_HE]          NVARCHAR (250)  NULL,
    [Real_quantity]             DECIMAL (10, 2) NOT NULL,
    [Margin]                    DECIMAL (10, 2) NOT NULL,
    [Revenue]                   DECIMAL (10, 2) NOT NULL,
    [purchase_price]            FLOAT (53)      NULL,
    [MAX_A_perc]                REAL            NULL,
    [MAX_A_amount]              REAL            NULL,
    [PPP_product_A]             FLOAT (53)      NULL,
    [Amount_tot_A]              REAL            NULL,
    [Perc_tot_A]                FLOAT (53)      NULL,
    [MAX_B_perc]                FLOAT (53)      NULL,
    [MAX_B_amount]              FLOAT (53)      NULL,
    [PPP_product_B]             FLOAT (53)      NULL,
    [Amount_tot_B]              FLOAT (53)      NULL,
    [Perc_tot_B]                FLOAT (53)      NULL,
    [MAX_D_Perc]                REAL            NULL,
    [MAX_D_Amount]              REAL            NULL,
    [PPP_product_D]             FLOAT (53)      NULL,
    [Amount_tot_D]              REAL            NULL,
    [Perc_tot_D]                FLOAT (53)      NULL,
    [C_catalog_price]           FLOAT (53)      NULL,
    [C_Netto_price]             FLOAT (53)      NULL,
    [Price_per_product_C]       FLOAT (53)      NULL,
    [Tot_C]                     FLOAT (53)      NOT NULL,
    [b_partA]                   INT             NOT NULL,
    [b_partB]                   INT             NOT NULL,
    [b_partC]                   INT             NOT NULL,
    [b_partD]                   INT             NOT NULL,
    [Yearmonth]                 INT             NULL,
    [Promotion_transaction]     INT             NOT NULL,
    [tot_Part_promotion]        FLOAT (53)      NOT NULL,
    [tot_Part_product]          FLOAT (53)      NOT NULL,
    [tot_Part_product_group]    FLOAT (53)      NOT NULL,
    [Tot_sellout_participation] FLOAT (53)      NOT NULL,
    [Tot_sellin_discount]       FLOAT (53)      NOT NULL
);

